// ----------------------------------------------------------------------------------------
//                              COPYRIGHT NOTICE
// ----------------------------------------------------------------------------------------
//
// The Source Code Store LLC
// ACTIVEGANTT SCHEDULER COMPONENT FOR C++ - ActiveGanttVC
// ActiveX Control
// Copyright (c) 2002-2017 The Source Code Store LLC
//
// All Rights Reserved. No parts of this file may be reproduced, modified or transmitted 
// in any form or by any means without the written permission of the author.
//
// ----------------------------------------------------------------------------------------
//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by AGVCCON.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_FMAIN                       103
#define IDD_FWBSPROJECT                 104
#define IDD_FCARRENTAL                  105
#define IDD_FCARRENTALBRANCH            106
#define IDD_FCARRENTALRESERVATION       107
#define IDD_FCARRENTALVEHICLE           108
#define IDD_FMSPROJECT11                109
#define IDD_FMSPROJECT12                110
#define IDD_FMSPROJECT14                111
#define IDD_FLOADXML                    112
#define IDD_FPRINTDIALOG                113
#define IDD_FPRINTPREVIEW               114
#define IDD_FWBSPROJECTTASKVIEW         115
#define IDD_FCUSTOMDRAWING              116
#define IDD_FFASTLOADING                117
#define IDD_FMILLISECONDINTERVAL        118
#define IDD_FSORTROWS                   119
#define IDD_FWBSPPROPERTIES             120
#define IDD_FDURATIONTASKS              121
#define IDD_FRCT_DAY                    122
#define IDD_FRCT_WEEK                   123
#define IDD_FRCT_MONTH                  124
#define IDD_FRCT_YEAR                   125
#define DRP_MODE                        126
#define IDD_FCUSTOMTICKMARKAREADRAW     127
#define IDR_MAINFRAME                   128
#define IDB_MAIN_BANNER                 129
#define IDB_FOLDEROPEN                  130
#define IDB_FOLDERCLOSED                131
#define IDB_AG                          132
#define IDB_INTERNET                    133
#define IDB_BLUEFOLDERCLOSED            134
#define IDB_BLUEFOLDEROPEN              135
#define IDD_FCUSTOMTICKMARKTEXTDRAW     136
#define IDD_FTEMPLATES                  137
#define IDD_FSTL_ANAKIWA_BLUE           138
#define IDB_FWBSPROJECT                 139
#define IDD_FSTL_MSP2003                140
#define IDR_MNU_WBSPROJECT              141
#define IDB_FMSPROJECT                  142
#define IDB_FCARRENTAL                  143
#define IDB_BITMAP2                     144
#define IDB_FLOADXML                    144
#define IDR_MNU_FCARRENTAL              145
#define IDD_FSTL_MSP2007                146
#define IDD_FSTL_MSP2010                147
#define IDD_FSTL_CR                     148
#define DRP_CONTROLTEMPLATES            149
#define DRP_OBJECTTEMPLATES             150
#define LBL_CONTROLTEMPLATES            151
#define LBL_OBJECTTEMPLATES             152
#define IDR_MNU_FMSPROJECT11            153
#define IDR_MNU_FMSPROJECT12            154
#define IDR_MNU_FMSPROJECT14            155
#define IDR_MNU_LOADXML                 156
#define IDB_BITMAP1                     160
#define IDB_FPRINTPREVIEW               160
#define IDB_GETTINGSTARTED              165
#define IDB_LOCALCHMDOCUMENTATION       166
#define IDB_ONLINEDOCUMENTATION         167
#define IDB_BITMAP3                     170
#define IDB_FPRINTPREVIEW2              170
#define IDB_FTEMPLATES                  177
#define IDC_TREE1                       1000
#define IDC_BANNER                      1001
#define IDC_LBLCOPYRIGHT                1002
#define IDC_ACTIVEGANTTVCCTL1           1005
#define IDC_GROUPBOX1                   1006
#define IDC_TXTBRANCHNAME               1008
#define IDC_TXTADDRESS                  1009
#define IDC_TXTCITY                     1010
#define IDC_TXTSTATE                    1011
#define IDC_TXTZIP                      1012
#define IDC_TXTPHONE                    1013
#define IDC_TXTMANAGERNAME              1014
#define IDC_TXTMANAGERMOBILE            1015
#define IDC_DRPCARTYPEID                1016
#define IDC_TXTNAME                     1017
#define IDC_DRPACRISS1                  1018
#define IDC_DRPACRISS2                  1019
#define IDC_DRPACRISS3                  1020
#define IDC_DRPACRISS4                  1021
#define IDC_TXTMOBILE                   1027
#define IDC_DTPPICKUP                   1028
#define IDC_DTPRETURN                   1029
#define IDC_TXTPICKUP                   1030
#define IDC_TXTRETURN                   1031
#define IDC_TXTDESCRIPTION              1033
#define IDC_TXTACRISS1                  1034
#define IDC_TXTACRISS2                  1035
#define IDC_TXTACRISS3                  1036
#define IDC_TXTACRISS4                  1037
#define IDC_CHKGPS                      1038
#define IDC_CHKFSO                      1039
#define IDC_CHKLDW                      1040
#define IDC_CHKPAI                      1041
#define IDC_CHKPEP                      1042
#define IDC_CHKALI                      1043
#define IDC_TXTGPS                      1044
#define IDC_TXTLDW                      1045
#define IDC_TXTPAI                      1046
#define IDC_TXTPEP                      1047
#define IDC_TXTALI                      1048
#define IDC_TXTCRF                      1049
#define IDC_TXTRCFC                     1050
#define IDC_TXTERF                      1051
#define IDC_TXTVLF                      1052
#define IDC_TXTWTB                      1053
#define IDC_TXTSURCHARGE                1054
#define IDC_TXTTAX                      1055
#define IDC_EDIT28                      1056
#define IDC_TXTESTIMATEDTOTAL           1056
#define IDC_LBLTASKNAME                 1056
#define IDC_TXTLICENSEPLATES            1057
#define IDC_TXTRATE                     1058
#define IDC_LBLACRISS1                  1059
#define IDC_LBLACRISS2                  1060
#define IDC_LBLACRISS3                  1061
#define IDC_LBLACRISS4                  1062
#define IDC_TXTNOTES                    1063
#define IDC_PICMAKE                     1064
#define IDC_LBLMODE                     1065
#define IDC_LBLTAX                      1066
#define IDC_PICTURE                     1067
#define IDC_CBOPRINTERNAME              1069
#define IDC_TXTSTARTPAGE                1070
#define IDC_TXTENDPAGE                  1071
#define IDC_TXTPAGEWIDTH                1072
#define IDC_TXTPAGEHEIGHT               1073
#define IDC_TXTSCALE                    1074
#define IDC_CBOORIENTATION              1075
#define IDC_TXTSDYEAR                   1076
#define IDC_TXTEDYEAR                   1077
#define IDC_TXTSDMONTH                  1078
#define IDC_TXTEDMONTH                  1079
#define IDC_TXTSDDAY                    1080
#define IDC_TXTSDHOUR                   1081
#define IDC_TXTEDDAY                    1082
#define IDC_TXTEDHOUR                   1083
#define IDC_TXTSDMINUTE                 1084
#define IDC_TXTEDMINUTE                 1085
#define IDC_TXTSDSECOND                 1086
#define IDC_TXTEDSECOND                 1087
#define IDC_CMDPREVIEW                  1088
#define IDC_LBLNUMBEROFPAGES            1089
#define IDC_MSFLEXGRID1                 1093
#define IDC_STATUS                      1094
#define IDC_HSCROLLBAR                  1095
#define IDC_VSCROLLBAR                  1096
#define IDC_FRAFORM                     1097
#define IDC_CMDPREVIOUSPAGE             1098
#define IDC_CMDNEXTPAGE                 1099
#define IDC_CMDXMARGINMINUS             1102
#define IDC_CMDXMARGINPLUS              1103
#define IDC_CMDYMARGINMINUS             1105
#define IDC_CMDYMARGINPLUS              1106
#define IDC_LBLPAGENUMBER               1107
#define IDC_LBLXMARGIN                  1109
#define IDC_LBLYMARGIN                  1110
#define IDC_SCROLLBARSSEP               1111
#define IDC_CMDSORTROWS                 1113
#define IDC_BUTTON1                     1114
#define IDC_CHKENFORCEPREDECESSORS      1115
#define IDC_COMBO1                      1116
#define IDC_CBOPREDECESSORMODE          1116
#define IDC_MSP2003CTRL1                1117
#define IDC_MSP2007CTRL1                1118
#define IDC_MSP2010CTRL1                1119
#define IDC_CBORESOLUTION               1121
#define IDC_TXTSTARTROW                 1122
#define IDC_TXTENDROW                   1123
#define IDC_CHKSHOWALLCOLUMNS           1124
#define IDC_CHKCOLUMNSINEVERYPAGE       1125
#define IDC_TXTCOLUMNS                  1126
#define IDC_NUMCOLUMNS                  1127
#define IDC_CHKKEEPCOLUMNSTOGETHER      1128
#define IDC_CHKKEEPTIMEINTERVALSTOGETHER 1129
#define IDC_CBOINTERVAL                 1130
#define IDC_TXTFACTOR                   1131
#define IDC_CHKHEADINGSINEVERYPAGE      1132
#define IDC_CHKKEEPROWSTOGETHER         1133
#define IDC_TXTMARGINLEFT               1134
#define IDC_TXTMARGINTOP                1135
#define IDC_TXTMARGINRIGHT              1136
#define IDC_TXTMARGINBOTTOM             1137
#define IDC_TXTDPIX                     1138
#define IDC_TXTDPIY                     1139
#define IDC_OPTALL                      1140
#define IDC_OPTFROM                     1141
#define IDC_NUMSTARTROW                 1142
#define IDC_NUMENDROW                   1143
#define IDC_NUMMARGINLEFT               1144
#define IDC_NUMMARGINTOP                1145
#define IDC_NUMMARGINRIGHT              1146
#define IDC_NUMMARGINBOTTOM             1147
#define IDC_NUMFACTOR                   1148
#define IDC_NUMDPIY                     1149
#define IDC_NUMDPIX                     1150
#define IDC_NUMSCALE                    1151
#define IDC_NUMSDYEAR                   1152
#define IDC_NUMEDYEAR                   1153
#define IDC_NUMSDMONTH                  1154
#define IDC_NUMEDMONTH                  1155
#define IDC_NUMSDDAY                    1156
#define IDC_NUMEDDAY                    1157
#define IDC_NUMSDHOUR                   1158
#define IDC_NUMEDHOUR                   1159
#define IDC_NUMSDMINUTE                 1160
#define IDC_NUMEDMINUTE                 1161
#define IDC_NUMSDSECOND                 1162
#define IDC_NUMEDSECOND                 1163
#define IDC_LBLDPIX                     1164
#define IDC_LBLDPIY                     1165
#define IDC_LBLINTERVAL                 1166
#define IDC_LBLFACTOR                   1167
#define ID_FILE_SAVEASXML               32771
#define ID_FILE_LOADFROMXML             32772
#define ID_FILE_PRINT32773              32773
#define ID_FILE_CLOSE32774              32774
#define ID_TREEVIEWPROPERTIES_CHECKBOXES 32775
#define ID_TREEVIEWPROPERTIES_PLUS      32777
#define ID_TREEVIEWPROPERTIES_FULLCOLUMNSELECT 32778
#define ID_FILE_SAVEASXML32779          32779
#define ID_FILE_LOADFROMXML32780        32780
#define ID_FILE_PRINT32781              32781
#define ID_FILE_CLOSE32782              32782
#define ID_FILE_SAVEASXML_CR            32783
#define ID_FILE_LOADFROMXML_CR          32784
#define ID_FILE_PRINT_CR                32785
#define ID_FILE_CLOSE_CR                32786
#define ID_FILE_SAVEASXML_WBSP          32787
#define ID_FILE_LOADFROMXML_WBSP        32788
#define ID_FILE_PRINT_WBSP              32789
#define ID_FILE_CLOSE_WBSP              32790
#define ID_EDIT_ROW_CR                  32791
#define ID_FILE_LOADMS                  32791
#define ID_DELETE_ROW_CR                32792
#define ID_FILE_SAVEMS                  32792
#define ID_CONVERT_TO_RENTAL_CR         32793
#define ID_FILE_PRINT32793              32793
#define ID_EDIT_TASK_CR                 32794
#define ID_FILE_CLOSE32794              32794
#define ID_DELETE_TASK_CR               32795
#define ID_FILE_LOADMS32795             32795
#define ID_FILE_SAVEMS32796             32796
#define ID_FILE_PRINT32797              32797
#define ID_FILE_CLOSE32798              32798
#define ID_FILE_LOADMS32799             32799
#define ID_FILE_SAVEMS32800             32800
#define ID_FILE_PRINT32801              32801
#define ID_FILE_CLOSE32802              32802
#define ID_FILE_LOADFROMXML32803        32803
#define ID_FILE_SAVEASXML32804          32804
#define ID_FILE_CLOSE32805              32805
#define ID_FILE_LOADXML                 32806
#define ID_FILE_SAVEXML                 32807
#define ID_TREEVIEWPROPERTIES_TREELINES 32808
#define ID_TREEVIEWPROPERTIES_IMAGES    32809

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        178
#define _APS_NEXT_COMMAND_VALUE         32810
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           153
#endif
#endif
